server:
  port: 8085

spring:
  application:
    name: fund-transfer-service
    bad_request: "BAD_REQUEST"
    conflict: "CONFLICT"
    not_found: "NOT_FOUND"
  cache:
    type: simple
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:fund_transfer_service}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:changeme}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics

resilience4j:
  circuitbreaker:
    instances:
      accountService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      accountService:
        maxAttempts: 3
        waitDuration: 100ms
  ratelimiter:
    instances:
      accountService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 1s

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      account-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL
