server:
  port: 8888

spring:
  application:
    name: configServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DHANUSH1323/banking-config.git
          default-label: main
          clone-on-start: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics