server:
  port: 8081

spring:
  application:
    name: account-service
    bad_request: "BAD_REQUEST"
    conflict: "CONFLICT"
    not_found: "NOT_FOUND"
  cache:
    type: simple
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB_NAME:account_service}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:changeme}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

custom:
  bad_request: 400
  conflict: 409
  ok: 200
  not_found: 404

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
